name: Build & Deploy

on:
  push:
    branches: [ "svelte" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Get NPM cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm cache dir)"

      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - run: npm run build --if-present

      - uses: a7ul/tar-action@master
        with:
          command: c
          cwd: "./"
          files: |
            build/
            package.json
            captain-definition
          outPath: deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME_V2 }}'
          token: '${{ secrets.APP_TOKEN_V2 }}'
